# -----------------------------------------------------------------------------
# AUTOGENERATED by host-terraform/main.tf
# Do not edit manually. Re-run terraform apply from host-terraform.
# -----------------------------------------------------------------------------
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  common_box = "${common_box}"

  config.vm.define "${control_name}" do |control|
    control.vm.box = common_box
    control.vm.hostname = "${control_name}"
    control.vm.network :private_network, ip: "${control_ip}"

    control.vm.provider "virtualbox" do |vb|
      vb.name = "${control_name}"
      vb.memory = ${control_memory}
      vb.cpus = ${control_cpus}
    end

    control.vm.synced_folder "..", "${project_mount_path}"
    control.vm.synced_folder ".", "${deployment_mount_path}"

    control.vm.provision "shell", path: "control-node/bootstrap-control.sh"
  end

  config.vm.define "${haproxy_name}" do |haproxy|
    haproxy.vm.box = common_box
    haproxy.vm.hostname = "${haproxy_name}"
    haproxy.vm.network :private_network, ip: "${haproxy_ip}"

    haproxy.vm.provider "virtualbox" do |vb|
      vb.name = "${haproxy_name}"
      vb.memory = ${haproxy_memory}
      vb.cpus = ${haproxy_cpus}
    end

    haproxy.vm.synced_folder ".", "${deployment_mount_path}"
  end

  config.vm.define "${microservices_name}" do |microservices|
    microservices.vm.box = common_box
    microservices.vm.hostname = "${microservices_name}"
    microservices.vm.network :private_network, ip: "${microservices_ip}"

    microservices.vm.provider "virtualbox" do |vb|
      vb.name = "${microservices_name}"
      vb.memory = ${microservices_memory}
      vb.cpus = ${microservices_cpus}
    end

    microservices.vm.synced_folder ".", "${deployment_mount_path}"
  end
end
